# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbrew < Formula
  desc "A simple TUI tool to make your brews bold."
  homepage "https://github.com/Valkyrie00/bold-brew"
  version "0.4.0"

  depends_on "go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Valkyrie00/bold-brew/releases/download/v0.4.0/bbrew_0.4.0_darwin_amd64.tar.gz"
    sha256 "a7b6b7a21581698adc056b72e469ebd382713238d07eb05c3bb98c6ab01fa4a4"

    def install
      bin.install "bbrew"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Valkyrie00/bold-brew/releases/download/v0.4.0/bbrew_0.4.0_darwin_arm64.tar.gz"
    sha256 "1f5d421677761f3437e52f00bac337c0205b7536b2abc69b67e42e8bc27a1616"

    def install
      bin.install "bbrew"
    end
  end

  test do
    system "#{bin}/bbrew --version"
  end
end
