# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BoldBrew < Formula
  desc "A simple TUI tool to make your brews bold."
  homepage "https://github.com/Valkyrie00/bold-brew"
  version "0.3.0"

  depends_on "go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Valkyrie00/bold-brew/releases/download/v0.3.0/bbrew_0.3.0_darwin_amd64.tar.gz"
    sha256 "d7f4e659108f6b1837dfb1d6ecf6e9939f89a4d7c6106c9c6ab7b0c6ebf38109"

    def install
      bin.install "bbrew"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Valkyrie00/bold-brew/releases/download/v0.3.0/bbrew_0.3.0_darwin_arm64.tar.gz"
    sha256 "0ef79166bddc61586f6dc155cbc8f4faa7ac31ccd88e1f4d1955ea7663cbe837"

    def install
      bin.install "bbrew"
    end
  end

  test do
    system "#{bin}/bbrew --version"
  end
end
